To gain access to the container in which an instance of an application is running, and run a command, you can use `kubectl exec`.

As with logging, you need to specify the particular `pod` you wan't to access, and if there are multiple containers running in the `pod`, specify which container using the `-c` or `--container` option.

[.console-input]
[source,execute]
----
kubectl exec $POD -- env
----

The command above has ran the command `env` inside the container, and then outputted the environment variables within the running container.

If you want to run an interactive terminal session, you need to ensure you use the `-i` or `--stdin` option, and the `-t` or `--tty` option.

[.console-input]
[source,execute]
----
kubectl exec -it $POD -- bash
----

From the interactive shell, you can view files in the file system.

[.console-input]
[source,execute]
----
ls -las
----

and can interact with the application processes:

```execute
ps x
```

The only processes you will be able to see are those for the instance of your application running in that container. You cannot see processes running in other containers of the same `pod`, or operating system processes.

Run:

```execute
exit
```

to end the interactive terminal session for the container.
