apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: national-parks-database
  labels:
    app: national-parks-database
    role: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
